# Làm quen với PyTorch

## Phần 1: Khám phá Tensor

### Task 1.1: Tạo Tensor

In [2]:
import torch
import numpy as np

In [3]:
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])



In [4]:
# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])



In [5]:
# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.9259, 0.4644],
        [0.0732, 0.7929]])



In [6]:
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


### Task 1.2: Các phép toán trên Tensor

1. Cộng `x_data` với chính nó

In [7]:
print(f"Cộng x_data với chính nó: \n{x_data} \n+\n{x_data} \n=", x_data + x_data)

Cộng x_data với chính nó: 
tensor([[1, 2],
        [3, 4]]) 
+
tensor([[1, 2],
        [3, 4]]) 
= tensor([[2, 4],
        [6, 8]])


2. Nhân `x_data` với 5

In [8]:
print(f"Nhân x_data với 5: \n{x_data} \n * 5 \n=", x_data * 5)

Nhân x_data với 5: 
tensor([[1, 2],
        [3, 4]]) 
 * 5 
= tensor([[ 5, 10],
        [15, 20]])


3. Nhân ma trận `x_data` với `x_data.T`

In [9]:
print(f"Nhân x_data với x_data.T: \n{x_data} \n@\n{x_data.T} \n=", x_data @ x_data.T)

Nhân x_data với x_data.T: 
tensor([[1, 2],
        [3, 4]]) 
@
tensor([[1, 3],
        [2, 4]]) 
= tensor([[ 5, 11],
        [11, 25]])


### Task 1.3: Indexing và Slicing

1. Lấy ra hàng đầu tiên

In [10]:
print(f"Hàng đầu tiên của \n{x_data} là:", x_data[0])

Hàng đầu tiên của 
tensor([[1, 2],
        [3, 4]]) là: tensor([1, 2])


2. Lấy ra cột thứ hai

In [11]:
print(f"Cột thứ hai của \n{x_data} là:", x_data[:,1])

Cột thứ hai của 
tensor([[1, 2],
        [3, 4]]) là: tensor([2, 4])


3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai

In [12]:
print(f"Giá trị ở hàng thứ hai, cột thứ hai của \n{x_data} là:", x_data[1,1])

Giá trị ở hàng thứ hai, cột thứ hai của 
tensor([[1, 2],
        [3, 4]]) là: tensor(4)


### Task 1.4: Thay đổi hình dạng Tensor

In [13]:
x_rand = torch.rand((4,4))
print(f"Tensor có shape (4,4):\n", x_rand)
x_rand = x_rand.reshape((16,1))
print(f"Tensor sau khi reshape (16,1):\n", x_rand)

Tensor có shape (4,4):
 tensor([[0.1016, 0.8452, 0.1346, 0.1692],
        [0.4619, 0.6292, 0.1144, 0.1913],
        [0.4614, 0.8410, 0.0188, 0.7149],
        [0.2466, 0.5514, 0.6366, 0.9481]])
Tensor sau khi reshape (16,1):
 tensor([[0.1016],
        [0.8452],
        [0.1346],
        [0.1692],
        [0.4619],
        [0.6292],
        [0.1144],
        [0.1913],
        [0.4614],
        [0.8410],
        [0.0188],
        [0.7149],
        [0.2466],
        [0.5514],
        [0.6366],
        [0.9481]])


## Phần 2: Tự động tính Đạo hàm với `autograd`

### Task 2.1: Thực hành với `autograd`

In [ ]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x000001D3D9FC80D0>
Đạo hàm của z theo x: tensor([18.])


In [15]:
# z.backward()

Khi gọi `z.backward()` lần thứ 2 thì bị lỗi do graph đã được giải phóng (xóa khởi bộ nhớ) sau lần backward đầu tiên để tiết kiệm bộ nhớ , nên khi gọi lần thứ 2 thì các tensor trung gian đã bị xóa và không thể backward được.

Cách khắc phục là có thể thêm tham số *retain_graph*: `z.backward(retain_graph=True)`

## Phần 3: Xây dựng Mô hình đầu tiên với `torch.nn`

### Task 3.1: Lớp `nn.Linear`

In [16]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3,5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[-0.9370,  0.3914],
        [-0.9572,  0.4896],
        [-0.7300,  0.1394]], grad_fn=<AddmmBackward0>)


### Task 3.2: Lớp `nn.Embedding`

In [17]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 9.4391e-01, -1.5359e+00, -3.1712e-01],
        [ 9.6256e-01, -6.3085e-01,  1.1433e-03],
        [ 9.5631e-01, -2.3418e-01, -3.4213e-01],
        [ 1.7969e-01, -3.3344e-01, -2.5940e-01]], grad_fn=<EmbeddingBackward0>)


### Task 3.3: Kết hợp thành một `nn.Module`

In [18]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output
    
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])


In [19]:
output_data

tensor([[[-0.5279, -0.3944],
         [ 0.0292,  0.0366],
         [-0.4793, -0.2219],
         [-0.0206, -0.0471]]], grad_fn=<ViewBackward0>)